export const usersDatabase = [
  {
    id: '1',
    name: 'Naame',
    surname: 'Suurname',
    type: 'Mentor',
    status: 'Active',
    averageGrade: 10,
  },
  {
    id: '2',
    name: 'Naaame',
    surname: 'Suuuurname',
    type: 'Participant',
    status: 'Archived',
    averageGrade: 10,
  },
  {
    id: '3',
    name: 'Naaaame',
    surname: 'Suuurname',
    type: 'Participant',
    status: 'Resigned',
    averageGrade: 10,
  },
  {
    id: '4',
    name: 'Naaaaaame',
    surname: 'Suuuuurname',
    type: 'Admin',
    status: 'Active',
    averageGrade: 10,
  },
  {
    id: '5',
    name: 'CName',
    surname: 'CSurname',
    type: 'Candidate',
    status: 'Active',
    averageGrade: 10,
  },
]
